# pull official base image
FROM node:14.15.4-alpine as build

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json .
COPY package-lock.json .

RUN npm ci --silent
RUN npm install react-scripts@3.4.1 -g
RUN npm install -g serve

# add app
COPY . ./

RUN npm run build





CMD ["serve" , "-s build"]