version: '3'
services:
    frontend:
        restart: unless-stopped
        build: ./prod
        ports:
            - 80:80/tcp
            - 443:443/tcp
        volumes:
          - ./conf.d:/etc/nginx/user.conf.d:ro
          - letsencrypt:/etc/letsencrypt
volumes:
    letsencrypt:

# docker-compose -f docker-compose.prod.yml